FROM ruby:3.3

WORKDIR /app

COPY Gemfile Gemfile.lock .

RUN bundle install

COPY entrypoint.sh /
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

EXPOSE 3000
CMD ["rails", "server", "-b", "0.0.0.0"]
